### ISSUE TITLE
Add ability to inject Yandex Metrika HTML tags in DEVELOPMENT mode as an option

### ISSUE THREAD

**Issue by yoda31217** [sgromkov/docusaurus-plugin-yandex-metrica#5]
As a developer I want to be able to test this plugin configuration in development mode. While I'm adding it first time.

Because I have huge docusaurus site which takes >1 hour to deploy to production. Which makes testing this plugin integration too  slow.

So, something like configuration field `enableInProductionOnly` would be very useful.

**Comment by sgromkov** [comment]
Hello @yoda31217 🙂

Thank you for your interest in the plugin.

I like your idea with `enableInProductionOnly` configuration field. I will implement it as soon as I can.

I'll be back with the result 🙌

**Comment by yoda31217** [comment]
@sgromkov 
I want to prepare a pull request by myself if yoiu do not mind. Give me just some time and I'll provide you with the link.

Thank you

**Comment by sgromkov** [comment]
@yoda31217 

Of course! If you have a desire to implement this feature yourself, I will be grateful for your help.

**Comment by yoda31217** [comment]
@sgromkov Added Pull Request: https://github.com/sgromkov/docusaurus-plugin-yandex-metrica/pull/6

**Comment by sgromkov** [comment]
Thank you so much @yoda31217 🙏

The new version released: https://github.com/sgromkov/docusaurus-plugin-yandex-metrica/releases/tag/v1.1.0

npm: https://www.npmjs.com/package/docusaurus-plugin-yandex-metrica
